---

- name: Clone the Slurm repository to the target
  ansible.builtin.git:
    repo: "{{ slurm_repo }}"
    dest: "{{ slurm_src_target_dir }}"
    version: "{{ slurm_version_tag}}"

- name: Configure Slurm
  ansible.builtin.shell: 
    chdir: "{{ slurm_build_dir }}"
    cmd: "{{ slurm_src_dir }}/configure {{ slurm_build_flags }}"

- name: Place make script
  when: place_make_script == true
  ansible.builtin.copy:
    src: "{{ make_script_src }}"
    dest: "{{ make_script_path }}"
    mode: "0755"

- name: Install slurm with make.py
  when: slurm_build_method == "make.py"
  ansible.builtin.script:
    chdir: "{{ slurm_build_dir }}"
    cmd: "{{ make_script_path }}"

# TODO
# - name: Install slurm with make
#   when: slurm_built_method == "make"

- name: Make tags with ctags
  when: maketags == true
  ansible.builtin.shell: |
    find {{ slurm_src_dir}}/ -name *.c -o -name *.h -o -name slurm.h.in > {{ slurm_src_dir}}/cscope.files
    ctags -R --language-force=Tcl --append=yes {{ slurm_src_dir}}/testsuite/expect/*
    cscope -i {{ slurm_src_dir}}/cscope.files -b"
    mv cscope.out {{ slurm_src_dir}}/
    mv tags {{ slurm_src_dir}}/
    