---
- name: Install build dependencies
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop: "{{ slurm_build_deps }}"
  when: build.with_dependencies

- name: Install JWT
  ansible.builtin.include_tasks: jwt.yml
  when: slurm_with_jwt

# REF: https://slurm.schedmd.com/quickstart_admin.html#manual_build
- name: Create build dir
  ansible.builtin.file:
    path: "{{ build.dir }}"
    state: directory
    owner: "{{ slurm_user }}"
    mode: "{{ slurm.conf.dir_mode }}"

- name: Configure Slurm
  ansible.builtin.command:
    chdir: "{{ build.dir }}"
    cmd: "{{ src.dir }}/configure {{ build.flags|join(' ') }}"
  register: configure_slurm
  changed_when: "configure_slurm.rc == 0"

- name: Install Slurm using a build script
  when: build.method == "script"
  ansible.builtin.script:
    chdir: "{{ build.dir }}"
    cmd: "{{ build.script }}"

# TODO [EXTERNAL] Configure installation with make
# - name: Install slurm with make
#   when: slurm_built_method == "make"

- name: Make tags with ctags
  when: build.with_tags
  ansible.builtin.shell: |
    find "{{ src.dir }}/" -name *.c -o -name *.h -o -name slurm.h.in > "{{ src.dir }}/cscope.files"
    ctags -R --language-force=Tcl --append=yes "{{ src.dir }}/testsuite/expect/*"
    cscope -i "{{ src.dir }}/cscope.files" -b
    mv cscope.out "{{ src.dir }}/"
    mv tags "{{ src.dir }}/"
  changed_when: true
