---
- name: Copy pam.d/slurm to nodes
  when: slurm_with_pam
  ansible.builtin.copy:
    src: pam_slurm
    dest: /etc/pam.d/slurm
    owner: "{{ slurm_conf_owner }}"
    group: "{{ slurm_conf_group }}"
    mode: "{{ slurm_conf_mode }}"

- name: Create log, state, and conf directories for Slurm
  when: build_slurm_auto
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ slurm_conf_owner }}"
    group: "{{ slurm_conf_group }}"
    mode: "{{ item.mode }}"
  loop:
    - {path: "{{ slurm_log_dir }}", mode: "{{ slurm_log_mode }}"}
    - {path: "{{ slurm_state_dir }}", mode: "{{ slurm_state_mode }}"}
    - {path: "{{ slurm_conf_dir }}", mode: "{{ slurm_dir_mode }}"}

- name: Make Slurm configuration files from template
  ansible.builtin.include_tasks: template.yml
  vars:
    owner: "{{ slurm_conf_owner }}"
    group: "{{ slurm_conf_group }}"
    mode: "{{ slurm_conf_mode }}"
  loop:
    - {src: "cgroup.conf.j2", dst: "{{ slurm_conf_dir }}/cgroup.conf", cond: slurm_with_cgroups, notify: Config change}
    - {src: "gres.conf.j2", dst: "{{ slurm_conf_dir }}/gres.conf", cond: slurm_with_gpu, notify: Config change}
    - {src: "topology.conf.j2", dst: "{{ slurm_conf_dir }}/topology.conf", cond: slurm_with_topo, notify: Config change}
    - {src: "slurm.conf.j2", dst: "{{ slurm_conf_dir }}/slurm.conf", cond: configure_slurm or reconfigure_slurm, notify: Config change}
    - {src: "slurm_rsyslog.conf", dst: "/etc/rsyslog.d/10_slurm_rsyslog.conf", cond: slurm_with_rsyslog}
    - {src: "cgroup_allowed_devices_file.j2", dst: "{{ slurm_conf_dir }}/cgroup_allowed_devices_file.conf", cond: slurm_with_cgroups, notify: Config change}
    - {src: "slurm_logrotate.j2", dst: "/etc/logrotate.d/slurm", cond: (slurm_log_dir is defined) and slurm_with_logrotate}
  loop_control:
    label: "File: {{ item.src }}"

- name: Make systemd services for Slurm from template
  ansible.builtin.include_tasks: template.yml
  vars:
    owner: "{{ slurm_conf_owner }}"
    group: "{{ slurm_conf_group }}"
    mode: "{{ slurm_conf_mode }}"
  loop:
    - {src: "slurmd.service.j2", dst: "/etc/systemd/system/slurmd.service", cond: configure_slurm or reconfigure_slurm, notify: Reload daemon}
    - {src: "slurmctld.service.j2", dst: "/etc/systemd/system/slurmctld.service", cond: (slurmctld_host == inventory_hostname), notify: Reload daemon}
    - {src: "slurmdbd.service.j2", dst: "/etc/systemd/system/slurmdbd.service", cond: (slurmctld_host == inventory_hostname), notify: Reload daemon}
    - {src: "slurmrestd.service.j2", dst: "/etc/systemd/system/slurmrestd.service", cond: "(slurmctld_host == inventory_hostname) and slurm_restapi", notify: Reload daemon}
    - {src: "sackd.service.j2", dst: "/etc/systemd/system/sackd.service", cond: slurm_with_sackd, notify: Reload daemon}
  loop_control:
    label: "Service: {{ item.src }}"

- name: Make slurmdbd.conf from template
  ansible.builtin.template:
    src: slurmdbd.conf.j2
    dest: "{{ slurm_conf_dir }}/slurmdbd.conf"
    owner: "{{ slurm_conf_owner }}"
    group: "{{ slurm_conf_group }}"
    mode: '0600'
    backup: "{{ slurm_conf_backup }}"
  when: slurmdbd_host == inventory_hostname
  notify: Restart slurmdbd
  no_log: true

- name: Configure plugstack
  ansible.builtin.include_tasks: plugstack.yml
  when: slurm_with_plugstack

# REF: https://slurm.schedmd.com/jwt.html#setup
- name: Configure Slurm for JWT
  when: slurm_with_jwt
  block:
    - name: Generate JWT Key
      become: true
      ansible.builtin.command:
        cmd: "dd if=/dev/random of={{ jwt_key_path }} bs=32 count=1"
        creates: "{{ jwt_key_path }}"
    - name: Set ownership of JWT key
      become: true
      ansible.builtin.file:
        path: "{{ jwt_key_path }}"
        owner: "{{ slurm_conf_owner }}"
        group: "{{ slurm_conf_group }}"
        mode: '600'


# REF: https://slurm.schedmd.com/high_throughput.html#sys_config
- name: Set sysctl values for high throughput systems
  when: slurm_manage_sysctl
  block:
    - name: Increase net.core.somaxconn for slurmctld
      ansible.posix.sysctl:
        name: net.core.somaxconn
        value: "{{ slurm_sysctl_core_somaxconn }}"
        sysctl_file: /etc/sysctl.d/50-slurm.conf

    - name: Increase net.ipv4.tcp_max_syn_backlog for slurmctld
      ansible.posix.sysctl:
        name: net.ipv4.tcp_max_syn_backlog
        value: "{{ slurm_sysctl_tcp_max_syn_backlog }}"
        sysctl_file: /etc/sysctl.d/50-slurm.conf
