---
# TODO Move these to ansible.builtin.synchronize with checksum option
# TODO Template out the systemd service files

# Copy local staging/bin into remote /usr/bin
  - name: copy bin
    become: true
    ansible.builtin.copy:
      src: "{{ slurm_staging_dir }}/bin/"
      dest: "{{ slurm_bin_dir }}"
      owner: root
      group: root
      mode: 755
      directory_mode: 755
      
# Copy local staging/sbin into remote /usr/local/sbin
  - name: copy sbin
    become: true
    ansible.builtin.copy:
      src: "{{ slurm_staging_dir }}/sbin/"
      dest: "{{ slurm_sbin_dir}}"
      owner: root
      group: root
      mode: 755
      directory_mode: 755

# Copy local lib into remote /usr/lib
  - name: copy lib
    become: true
    ansible.builtin.copy:
      src: "{{ slurm_staging_dir }}/lib/"
      dest: "{{ slurm_lib_dir }}"
      owner: root
      group: root
      mode: 755
      directory_mode: 755

# Copy local man into remote /usr/share/man
  - name: copy man
    become: true
    ansible.builtin.copy:
      src: "{{ slurm_staging_dir }}/share/man/"
      dest: "{{ slurm_man_dir }}"
      owner: root
      group: root
      mode: 755
      directory_mode: 755