---
# TODO These take a while and I should first try to check whether slurm is already installed
# TODO Template out the systemd service files

# Copy local staging/bin into remote /usr/bin
  - name: copy bin
    become: true
    ansible.builtin.copy:
      src: "{{ slurm_staging_dir }}/bin/"
      dest: /usr/bin
      owner: root
      group: root
      mode: 755
      
# Copy local staging/sbin into remote /usr/local/sbin
  - name: copy sbin
    become: true
    ansible.builtin.copy:
      src: "{{ slurm_staging_dir }}/sbin/"
      dest: /usr/local/sbin
      owner: root
      group: root
      mode: 755

# Copy local lib into remote /usr/lib
  - name: copy lib
    become: true
    ansible.builtin.copy:
      src: "{{ slurm_staging_dir }}/lib/"
      dest: /usr/lib
      owner: root
      group: root
      mode: 755

# Copy local man into remote /usr/share/man
  - name: copy man
    become: true
    ansible.builtin.copy:
      src: "{{ slurm_staging_dir }}/share/man/"
      dest: /usr/share/man
      owner: root
      group: root
      mode: 755