---
# TODO Only run if JWT branch is different
- name: Install build dependencies
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  when: install_jwt_build_deps
  loop:
    - libjwt
    - autoconf
    - automake
    - libtool
    - jansson-devel

- name: Create JWT directory
  ansible.builtin.file:
    path: "{{ jwt_src_target }}"
    state: directory
    mode: '0755'

- name: Clone the repository to the target
  ansible.builtin.git:
    repo: "{{ jwt_repo }}"
    dest: "{{ jwt_src_target }}/libjwt"
    version: "{{ jwt_branch }}"
    single_branch: true
    force: true

- name: Configure JWT
  become: true
  ansible.builtin.shell:
    chdir: "{{ jwt_src_target }}/libjwt"
    cmd: |
      set -o pipefail && autoupdate
      autoreconf --force --install
      ./configure --prefix="{{ jwt_conf_prefix }}"
      make -j

- name: Install JWT
  become: true
  ansible.builtin.command:
    cmd: make install
    chdir: "{{ jwt_src_target }}/libjwt"
