---
- name: Preflight checks to determine tasking
  ansible.builtin.include_tasks: preflight.yml

- name: Configure slurm user and group
  ansible.builtin.include_tasks: user.yml
  when: configure_slurm_user or build_slurm_auto

- name: Build
  ansible.builtin.include_tasks: build.yml
  when: build_slurm or build_slurm_auto

- name: Configure
  ansible.builtin.include_tasks: configure.yml
  when: (configure_slurm or reconfigure_slurm) or build_slurm_auto

# TODO inventory_hostname is unreliable and should be altered to something like ansible_hostname in all cases
# TASK REF: https://slurm.schedmd.com/accounting.html#mysql-configuration
- name: Set up Mariadb
  ansible.builtin.include_tasks: mariadb.yml
  when: (slurmdbd_host == inventory_hostname) and (configure_slurm_mariadb or (build_slurm_auto and mariadb_when_autobuild))

# TASK REF: https://slurm.schedmd.com/authentication.html#munge
- name: Configure Munge
  ansible.builtin.include_tasks: munge.yml
  when: configure_munge or (build_slurm_auto and munge_when_autobuild)

- name: Set Slurm Systemd Service State
  ansible.builtin.include_tasks: systemd.yml
