---

- name: Configure slurm user and group
  ansible.builtin.include_tasks: user.yml

- name: Build
  ansible.builtin.include_tasks: build.yml
  when: build_slurm

- name: Install
  ansible.builtin.include_tasks: install.yml
  when: install_slurm

- name: Configure
  ansible.builtin.include_tasks: configure.yml
  when: configure_slurm

- name: Set up Mariadb
  ansible.builtin.include_tasks: mariadb.yml
  when: slurmdbd_host == inventory_hostname

- name: Configure Munge
  ansible.builtin.include_tasks: munge.yml

- name: Set up slurmdbd
  ansible.builtin.include_tasks: slurmdbd.yml
  when: slurmdbd_host == inventory_hostname

- name: Set up slurmctld
  ansible.builtin.include_tasks: slurmctld.yml
  when: slurmctld_host == inventory_hostname

- name: Set up slurmd's
  ansible.builtin.include_tasks: slurmd.yml
  when: "'slurm_compute' in group_names"
