---
- name: Preflight checks to detemine tasking
  ansible.builtin.include_tasks: preflight.yml
  when: build_slurm_auto

- name: Configure slurm user and group
  ansible.builtin.include_tasks: user.yml
  when: configure_slurm_user or build_slurm_auto

- name: Build
  ansible.builtin.include_tasks: build.yml
  when: build_slurm or build_slurm_auto

- name: Configure
  ansible.builtin.include_tasks: configure.yml
  when: configure_slurm or build_slurm_auto

- name: Set up Mariadb
  ansible.builtin.include_tasks: mariadb.yml
  when: (slurmdbd_host == inventory_hostname) and (configure_slurm_mariadb or (build_slurm_auto and mariadb_when_autobuild))

- name: Configure Munge
  ansible.builtin.include_tasks: munge.yml
  when: configure_munge or (build_slurm_auto and munge_when_autobuild)

- name: Set up slurmdbd
  ansible.builtin.include_tasks: slurmdbd.yml
  when: (slurmdbd_host == inventory_hostname) and (configure_slurmdbd or build_slurm_auto)

- name: Set up slurmctld
  ansible.builtin.include_tasks: slurmctld.yml
  when: (slurmctld_host == inventory_hostname) and (configure_slurmctld or build_slurm_auto)

- name: Set up slurmds
  ansible.builtin.include_tasks: slurmd.yml
  when: (inventory_hostname in groups['slurm_compute']) and (configure_slurmd or build_slurm_auto)
