---

- name: Configure slurm user and group
  ansible.builtin.include_tasks: user.yml

- name: Build
  ansible.builtin.include_tasks: build.yml

- name: Install
  ansible.builtin.include_tasks: install.yml

- name: Configure
  ansible.builtin.include_tasks: configure.yml

- name: Set up mariadb
  ansible.builtin.include_tasks: mariadb.yml

- name: Set up slurmdbd
  ansible.builtin.include_tasks: slurmdbd.yml
  when: slurmdbd_host == inventory_hostname

- name: Set up slurmctld
  ansible.builtin.include_tasks: slurmctld.yml
  when: slurmctld_host == inventory_hostname

- name: Set up slurmd's
  ansible.builtin.include_tasks: slurmd.yml
  when: "'slurm_compute' in group_names"
