---

- name: Does the munge.key exist?
  ansible.builtin.stat:
    path: /etc/munge/munge.key
  register: mungekeystat
  check_mode: no
  ignore_errors: True

- name: Create munge key
  ansible.builtin.command:
    cmd: /usr/sbin/mungekey
    creates: /etc/munge/munge.key
  register: mungekeygen
  when: mungekeystat is defined and mungekeystat.stat.exists == False

- name: Restart munge
  ansible.builtin.systemd_service:
    name: munge
    state: restarted
  when: mungekeygen.changed and mungekeygen is defined

- name: Set mungekey permissions
  ansible.builtin.file:
    path: /etc/munge/munge.key
    owner: munge
    group: munge
    mode: "0600"

- name: Start and enable munge on service nodes
  ansible.builtin.systemd_service:
    name: munge
    state: started
    enabled: yes
