---
- name: Determine slurmd versions
  ansible.builtin.command:
    cmd: slurmd --version
  when: inventory_hostname in groups['slurm_compute']
  changed_when: true
  register: slurmd_version
  ignore_errors: true

- name: Determine slurmctld version
  ansible.builtin.command:
    cmd: slurmctld --version
  when: slurmctld_host == inventory_hostname
  changed_when: true
  register: slurmctld_version
  ignore_errors: true

- name: Determine slurmdbd version
  become: true
  ansible.builtin.command:
    cmd: slurmdbd -V
  when: slurmdbd_host == inventory_hostname
  changed_when: true
  register: slurmdbd_version
  ignore_errors: true

- name: Set Slurmd version fact
  ansible.builtin.set_fact:
    build_slurm_auto: "{{ not slurm_version in slurmd_version.stdout | default('true') }}"

- name: Set Slurmctld version fact
  ansible.builtin.set_fact:
    build_slurm_auto: "{{ not slurm_version in slurmctld_version.stdout | default('true') }}"
  when: slurmctld_host == inventory_hostname

- name: Set Slurmdbd version fact
  ansible.builtin.set_fact:
    build_slurm_auto: "{{ not slurm_version in slurmdbd_version.stdout | default('true') }}"
  when: slurmdbd_host == inventory_hostname
