---
- name: Start and enable slurmdbd
  ansible.builtin.systemd_service:
    name: slurmdbd
    state: started
    enabled: true
  register: slurmdbd_start

- name: Restart slurmdbd
  ansible.builtin.systemd_service:
    name: slurmdbd
    state: started
    enabled: true
  when: slurmdbd_place.changed and not slurmdbd_start.changed
