---
- name: Template in slurmd.service file
  ansible.builtin.template:
    src: "slurmd.service.j2"
    dest: /etc/systemd/system/slurmd.service
    owner: "{{ slurm_conf_owner }}"
    group: "{{ slurm_conf_group }}"
    mode: "{{ slurm_conf_mode }}"

- name: Template in slurmctld.service file
  ansible.builtin.template:
    src: "slurmctld.service.j2"
    dest: /etc/systemd/system/slurmctld.service
    owner: "{{ slurm_conf_owner }}"
    group: "{{ slurm_conf_group }}"
    mode: "{{ slurm_conf_mode }}"
  when: (slurmctld_host == inventory_hostname)

- name: Template in slurmdbd.service file
  ansible.builtin.template:
    src: "slurmdbd.service.j2"
    dest: /etc/systemd/system/slurmdbd.service
    owner: "{{ slurm_conf_owner }}"
    group: "{{ slurm_conf_group }}"
    mode: "{{ slurm_conf_mode }}"
  when: (slurmctld_host == inventory_hostname)

- name: Template in sackd.service file
  ansible.builtin.template:
    src: sackd.service.j2
    dest: /etc/systemd/system/sackd.service
    owner: "{{ slurm_conf_owner }}"
    group: "{{ slurm_conf_group }}"
    mode: "{{ slurm_conf_mode }}"
  when: slurm_with_sackd

- name: Reload systemd daemon
  become: true
  ansible.builtin.systemd_service:
    daemon_reload: true
