---
- name: Make from template {{ item.src }}
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    owner: "{{ owner }}"
    group: "{{ group }}"
    mode: "{{ mode }}"
    backup: "{{ slurm_conf_backup }}"
  when: "{{ item.cond }}"
  notify: "{{ item.notify | default('') }}"
  # TODO Find out idiomatic way to do below
  # register: "{{ item.src }}_placed"
