---
- name: Make from template {{ item.src }}
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    owner: "{{ owner }}"
    group: "{{ group }}"
    mode: "{{ mode }}"
    backup: "{{ slurm_backup_conf }}"
  when: "{{ item.cond }}"
  register: "{{ item.src }}_placed"
