---
    # Set slurm user and group locally on every host if uid/gid given
  - name: add slurm unix group
    ansible.builtin.group:                                                                               
      name: slurm
      state: present
      system: no
    register: reg_slurm_unixgroup

  - name: add slurm unix user
    ansible.builtin.user:
      name: slurm
      shell: /sbin/nologin
      create_home: no
      system: no
      append: yes
      group: slurm
      state: present
    register: reg_slurm_unixuser
