---
  - name: Add slurm unix group
    ansible.builtin.group:                                                                               
      name: slurm
      state: present
      system: no

  - name: Add slurm unix user
    ansible.builtin.user:
      name: slurm
      shell: /sbin/nologin
      create_home: no
      system: no
      groups: slurm
      state: present
