---
- name: Add slurm unix group
  ansible.builtin.group:
    name: "{{ slurm_group }}"
    state: present
    system: false

- name: Add slurm unix user
  ansible.builtin.user:
    name: "{{ slurm_user }}"
    shell: /sbin/nologin
    create_home: false
    system: false
    groups: "{{ slurm_group }}"
    state: present

# REF: https://slurm.schedmd.com/rest_quickstart.html#systemd
- name: Add slurmrestd user
  ansible.builtin.user:
    name: slurmrestd
    create_home: false
    system: true
    shell: /sbin/nologin
  when: slurm_restapi
