---
- name: Restart mariadb
  ansible.builtin.systemd_service:
    name: mariadb
    state: restarted
  when: (slurmdbd_host == inventory_hostname)

- name: Restart munge
  ansible.builtin.systemd_service:
    name: munge
    state: restarted

- name: Reload daemon
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart slurmctld
  ansible.builtin.systemd_service:
    name: slurmctld
    state: restarted
  listen: Config change
  when: (slurmctld_host == inventory_hostname)

- name: Restart slurmd
  ansible.builtin.systemd_service:
    name: slurmd
    state: restarted
  listen: Config change
  when: (inventory_hostname in groups['slurm_compute'])

- name: Restart slurmdbd
  ansible.builtin.systemd_service:
    name: slurmdbd
    state: restarted
  when: (slurmdbd_host == inventory_hostname)

- name: Scontrol reconfig
  become: true
  ansible.builtin.command:
    cmd: scontrol reconfigure
  when: slurmctld_host == inventory_hostname
  changed_when: true
  listen: Config change
