---
# Source Configuration
slurm_src:
  repo: "https://github.com/SchedMD/slurm"
  tag: "slurm-25-05-1-1"
  version: "25.05"
  major_version: "25"

# Build directories
slurm_src_dir: "{{ user_homedir }}/slurm/{{ slurm_version }}"
slurm_build_dir: "{{ slurm_src_dir }}/{{ inventory_hostname }}/build"

slurm_sbin_dir: /usr/local/sbin

# ./configure flags
# Available options inclue --enable-developer or --enable-multiple-slurmd
# For none, set to ""
slurm_configure_flags:
  - "--enable-developer"
  - "--sysconfdir={{ slurm_conf_dir }}"
  - "{{ slurm_jwt_configure_flags }}"

# Method by which to build slurm. Options are "make.py" or "make"
slurm_build_method: "script"

# Make script config
place_make_script: true
build_script_path: "{{ user_homedir }}/slurm/scripts/make.py"

# Maketags with ctags
maketags: false

# Slurm build dependencies
install_build_deps: false

# REF: https://slurm.schedmd.com/quickstart_admin.html#prereqs
slurm_build_deps:
  - "@development-tools"
  - clang
  - clang-analyzer
  - expect
  - gtk2-devel
  - hdf5-devel
  - http-parser-devel
  - hwloc-devel
  - json-c-devel
  - libcurl-devel
  - libjwt-devel
  - libevent-devel
  - libibmad-devel
  - libibumad-devel
  - OpenIPMI
  - libssh2-devel
  - libyaml-devel
  - lua-devel
  - lz4-devel
  - man
  - man2html
  - mariadb
  - mariadb-devel
  - munge
  - munge-devel
  - ncurses-devel
  - numactl-devel
  - openssl-devel
  - pam-devel
  - perl-ExtUtils-MakeMaker
  - perl-ExtUtils-ParseXS
  - pmix-devel
  - python3
  - readline-devel
  - rrdtool-devel
  - vim
  - which
  - dbus-devel
