---
src:
  repo: "https://github.com/SchedMD/slurm"
  tag: "slurm-25-05-1-1"
  version: "25"
  dir: "{{ user_homedir }}/slurm/{{ src.version }}"

build:
  dir: "{{ src.dir }}/{{ inventory_hostname }}/build"
  flags: "--enable-developer --sysconfdir={{ slurm_conf_dir }} {{ slurm_jwt_configure_flags }}"
  method: "script"
  script: "/home/vhafener/slurm/scripts/make.py"
  with_tags: false
  
  # REF: https://slurm.schedmd.com/quickstart_admin.html#prereqs
  with_dependencies: false
  dependencies:
    - "@development-tools"
    - clang
    - clang-analyzer
    - expect
    - gtk2-devel
    - hdf5-devel
    - http-parser-devel
    - hwloc-devel
    - json-c-devel
    - libcurl-devel
    - libjwt-devel
    - libevent-devel
    - libibmad-devel
    - libibumad-devel
    - OpenIPMI
    - libssh2-devel
    - libyaml-devel
    - lua-devel
    - lz4-devel
    - man
    - man2html
    - mariadb
    - mariadb-devel
    - munge
    - munge-devel
    - ncurses-devel
    - numactl-devel
    - openssl-devel
    - pam-devel
    - perl-ExtUtils-MakeMaker
    - perl-ExtUtils-ParseXS
    - pmix-devel
    - python3
    - readline-devel
    - rrdtool-devel
    - vim
    - which
    - dbus-devel
