---
slurm:
  cgroups:
    mountpoint: "/sys/fs/cgroup"
    constrain:
      cores: "yes"
      ram: "no"
      swap: "no"
      devices: "no"
    allowed_space:
      ram: "100.1"
      swap: "120"
    min:
      ram: "500"
    task_affinity: "no"

  logrotate:
    rotate: "8"
    interval: "weekly"
    signal: "-HUP"
